- name: Prometheus Server
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server


- name: Exporter Server
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter