
##if [ "${schema_type}" == "mongo" ]; then
#print_head "Copy mongodb repo"
#cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#status_check $?

#print_head "Install mongo client"
#yum install mongodb-org-shell -y &>>${log_file}
#status_check $?

#print_head "Load Schema"
#mongo --host mongodb-dev.devops25.online </app/schema/${component}.js &>>${log_file}
#status_check $?
#elif [ "${schema_type}" == "mysql" ]; then
#print_head "Installing mysql"
#yum install mysql -y &>>${log_file}
#status_check $?

#print_head "Load Schema"
#mysql -h mysql-dev.devops25.online -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>${log_file}
#status_check $?

#fi

- name: Copy Mongo Repo
  ansible.builtin.copy:

